const flowers = [
  {
    id: 1,
    name: 'Daisy',
    price: 5,
    info: 'The sweet simplicity and genuine beauty of the daisy have made the flower an international emblem of innocence and purity. Its fresh, crisp appearance has come to symbolize new beginnings, and its bright, spirit-lifting colors are known to spread happiness like wildfire.',
    url: 'https://i.ibb.co/4SpyXqL/daisy.png',
    bestseller: true,
    rate: 4.5,
    rewiev: 'This flower is the best gift i’ve ever got',
  },
  {
    id: 2,
    name: 'Sunflower',
    price: 7,
    info: 'Make every day brighter with our abundant bouquet of fresh sunflowers. These radiant, long-lasting blooms bring that just-picked-from-the-meadow feeling to birthdays, get well wishes, or any day you want to make someone you care about smile.',
    url: 'https://i.ibb.co/NYMwQL9/Rectangle-58.jpg',
    bestseller: true,
    rate: 4.6,
    rewiev: 'This flower is the best gift i’ve ever got',
  },
  {
    id: 3,
    name: 'White Rose',
    price: 10,
    info: 'The white rose is a flower of purity, innocence, and new beginnings. Its delicate petals are like snow, and its sweet scent is a breath of fresh air. Now it became associated with weddings and bridal bouquets.',
    url: 'https://i.ibb.co/QdJTH8k/Rectangle-58.jpg',
    bestseller: true,
    rate: 4.7,
    rewiev: 'This flower is the best gift i’ve ever got',
  },
  {
    id: 4,
    name: 'Periwinkle',
    price: 8,
    info: 'Periwinkle represents serenity, calmness, winter, and ice. It can also symbolize blossoming friendships, sentimental memories, and everlasting love.',
    url: 'https://i.ibb.co/JFhjdK0/Rectangle-58.jpg',
    bestseller: true,
    rate: 4.8,
    rewiev: 'This flower is the best gift i’ve ever got',
  },
  {
    id: 5,
    name: 'Pink Rose',
    price: 9,
    info: 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.',
    url: 'https://i.pinimg.com/474x/5a/98/d7/5a98d752dc04ff8516c675919bc0fdb4.jpg',
    bestseller: false,
    rate: 4.2,
    review:
      'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
  },
  {
    id: 6,
    name: 'Pion',
    price: 4,
    info: 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
    url: 'https://img.freepik.com/premium-photo/pion-isolated-colored-background-pink-gentle-soft-peony-flower-stylish-flowers-march-8-pions_121234-220.jpg',
    bestseller: false,
    rate: 3.7,
    review:
      'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
  },
  {
    id: 7,
    name: 'Gerbera',
    price: 3,
    info: 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.',
    url: 'https://dy1yydbfzm05w.cloudfront.net/media/catalog/product/g/e/gerbera_daisy_atomic_tangerine_gerbera_daisy_stem_2.jpg',
    bestseller: false,
    review: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    rate: 2.9,
  },
  {
    id: 8,
    name: 'Tulip',
    price: 4,
    info: 'Curabitur convallis.',
    url: 'https://cdn11.bigcommerce.com/s-1b9100svju/images/stencil/1280x1280/products/488/931/DETA-128__69986.1631199402.jpg?c=1',
    bestseller: false,
    review:
      'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.',
    rate: 2,
  },
];

export { flowers };
